name: test :-

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  MANIFEST: https://raw.githubusercontent.com/Uday0011/Ash/master/SaitamaRobot/modules/thonkify_dict.py
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: GIT CLONE THONK NOT RECOVERY
         run: |
             mkdir work
             cd work
             sudo apt-get install git wget
             wget $MANIFEST 
             
       - uses: actions/upload-artifact@v2
         with:
          name: thonkify_dictpy
          path: work/out/target/product/*/thonkify_dict.py
